### PR TITLE
fix(reports): add tooltip to the late reports

### PR DESCRIPTION
**Pull request by FussuChalice**
# Description

Add small info icon + tooltip explaining how the mechanics of late reports work in Organized: Mark a report as 'Late' if the monthly branch office report has already been submitted. Late report will automatically be included in next month's submission. 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rhahao** [comment]
Task linked: [CU-86c1arg2b [FEAT] Tooltip to the late reports](https://app.clickup.com/t/86c1arg2b)

**Comment by FussuChalice** [comment]
@rhahao Do you think we should create a new component, just for these purposes (tooltip with icon and checkbox)? Then we can get rid of code duplication. Or is this okay?

**Comment by rhahao** [comment]
@FussuChalice: feel free to change it if you are able to do so. Thank you.

**Pull request merged**
