### PR TITLE
[FEAT] CPE - SC - Assignments Checklist

### PR DESCRIPTION
**Pull request by Logan08691**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

- **New Features**
	- Expanded the functionality of the `ComponentPreview` to render multiple `AssignmentsCheckList` components with different configurations and checkboxes for various meeting roles.
- **Style**
	- Updated styles for improved UI, including checkboxes, labels, and typography.

### CODE REVIEW

**Comment by rhahao** [comment]
Task linked: [CU-86by10wye assignments-checklist](https://app.clickup.com/t/86by10wye)

**Review by rhahao — CHANGES_REQUESTED** [review]
@Logan08691: thanks for this PR. However, I do believe that the header of the checklist should behave like the [Indeterminate Checkbox](https://mui.com/material-ui/react-checkbox/#indeterminate) in MUI docs. @ux-git, can you confirm this? Thanks.

**Comment by ux-git** [comment]
Yes, it should behave like this: https://www.tutorialspoint.com/how-to-set-indeterminate-state-in-the-checkbox-in-material-ui

**Comment by Logan08691** [comment]
@rhahao @ux-git Thanks! I missed that 😄

**Comment by FussuChalice** [comment]
@Logan08691 @rhahao @ux-git Hi all!  I saw this pull request.  I think you need to move the image to another folder, then convert it into a component.  This icon, in my opinion, is not an illustration.  You can ask reviewers about converting icons.

**Review by FussuChalice — CHANGES_REQUESTED** [review]
@Logan08691 Can you please change ```import Typography from '../typography';``` to ```import CustomTypography from '.@components/typography/index';``` to improve the dynamics of the project. In index.tsx

**Comment by Logan08691** [comment]
> @Logan08691 @rhahao @ux-git Hi all! I saw this pull request. I think you need to move the image to another folder, then convert it into a component. This icon, in my opinion, is not an illustration. You can ask reviewers about converting icons.

I deleted it 😄

**Review by rhahao — CHANGES_REQUESTED** [review]
@Logan08691, @FussuChalice: one last comment on this: could please remove (if needed, replace) the word `CPE`? All the previous occurrences are all deleted in the codebase.

**Comment by Logan08691** [comment]
> @Logan08691, @FussuChalice: one last comment on this: could please remove (if needed, replace) the word `CPE`? All the previous occurrences are all deleted in the codebase.

Done!

**Pull request merged**
