### PR TITLE
Cu 86bwch6u6 view weekly schedules page alonzo

### PR DESCRIPTION
**Pull request by Al11o**
First step of the page. 
Waiting for : 
- devs instruction about my file structures
- designers reviews about my integration

### CODE REVIEW

**Comment by rhahao** [comment]
Task linked: [CU-86bwch6u6 View weekly schedules page](https://app.clickup.com/t/86bwch6u6)

**Comment by ux-git** [comment]
Design-vice everything looks great so far. Any code comments, @rhahao?

**Review by rhahao — CHANGES_REQUESTED** [review]
@Al11o: thanks for working on this one. About the folder&file structure, could you please move most of the files in `pages/meeting/schedules` to `features/meetings`? Generally in the `pages` folder, we try to keep only the `index.tsx` file for the page. Other components will be imported from the `features` folder. Feel free to create folders in the `features/meetings` folder to move your files.

**Comment by rhahao** [comment]
@Al11o: additionally, I’ve now included the icon for male and female in the codebase so these icons can be imported like any other icons, so you don’t need to recreate them anymore in this PR. Thanks.

**Pull request merged**
