### PR TITLE
Create loading circle component

### PR DESCRIPTION
**Pull request by yrakhwas**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by yrakhwas** [comment]
Create pull-request on main-next branch

**Review by rhahao — CHANGES_REQUESTED** [review]
@yrakhwas: could you please resolve the merge conflicts in this PR? Thanks.

**Comment by yrakhwas** [comment]
Changing data to resolve the conflict

**Comment by yrakhwas** [comment]
Changing data to resolve the conflict

**Comment by yrakhwas** [comment]
Changing data to resolve the conflict

**Review by rhahao — APPROVED** [review]

**Pull request merged**
