### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by Stev24**
# Description

This will add the big progressbar.

### CODE REVIEW

**Comment by rhahao** [comment]
@Stev24: thanks for this PR. First, would you please resolve the conflicts reported below? Thanks.

**Comment by Stev24** [comment]
How did I get so many errors not related to my code ?

**Comment by rhahao** [comment]
I am sure it is related to the last change you made but GitHub failed to merge it correctly with the last changes on `main-next`, then it delegates the action to merge your changes with actual code with this merge conflicts error.
image

**Comment by rhahao** [comment]
@Stev24: I am closing this one for now. Feel free to send a new one later. Thank you.

**Pull request closed without merging**
